import type { Lead, Call, CampaignSettings } from "./types";

// Demo dataset for the UI while the live Supabase/ElevenLabs wiring is stubbed.
// Timestamps are anchored around 2026-07-16 so relative times read sensibly.

const T = (h: number, m = 0) =>
  new Date(2026, 6, 16, h, m, 0).toISOString();
const DAY = (d: number, h = 10) =>
  new Date(2026, 6, d, h, 0, 0).toISOString();

export const campaignSettings: CampaignSettings = {
  name: "Business Financing — Q3 Outbound",
  active: true,
  windowStart: "09:00",
  windowEnd: "18:00",
  callsPerTick: 3,
  dailyCap: 30,
  maxAttempts: 2,
  numbers: ["+14155550142", "+16505550188"],
};

export const leads: Lead[] = [
  {
    id: "ld_01",
    name: "Marcus Reyes",
    businessName: "Reyes Family HVAC",
    phone: "+14155550142",
    industry: "HVAC",
    state: "CA",
    timezone: "America/Los_Angeles",
    status: "interested",
    attempts: 1,
    lastCalledAt: T(11, 4),
    consentSource: "web-form",
    uploadedAt: DAY(15),
  },
  {
    id: "ld_02",
    name: "Dr. Priya Nadella",
    businessName: "Bright Smile Dental",
    phone: "+12125550171",
    industry: "Dental",
    state: "NY",
    timezone: "America/New_York",
    status: "interested",
    attempts: 1,
    lastCalledAt: T(10, 22),
    consentSource: "web-form",
    uploadedAt: DAY(15),
  },
  {
    id: "ld_03",
    name: "Tony Marchetti",
    businessName: "Marchetti's Trattoria",
    phone: "+13125550133",
    industry: "Restaurant",
    state: "IL",
    timezone: "America/Chicago",
    status: "callback",
    attempts: 1,
    lastCalledAt: T(12, 40),
    consentSource: "web-form",
    uploadedAt: DAY(15),
  },
  {
    id: "ld_04",
    name: "Sandra Okafor",
    businessName: "Okafor Plumbing Co.",
    phone: "+17135550119",
    industry: "Plumbing",
    state: "TX",
    timezone: "America/Chicago",
    status: "interested",
    attempts: 2,
    lastCalledAt: T(13, 8),
    consentSource: "list-partner",
    uploadedAt: DAY(15),
  },
  {
    id: "ld_05",
    name: "Kevin Zhang",
    businessName: "Summit IT Solutions",
    phone: "+14085550164",
    industry: "IT Services",
    state: "CA",
    timezone: "America/Los_Angeles",
    status: "not_interested",
    attempts: 1,
    lastCalledAt: T(9, 51),
    consentSource: "web-form",
    uploadedAt: DAY(15),
  },
  {
    id: "ld_06",
    name: "Rosa Delgado",
    businessName: "Delgado Auto Body",
    phone: "+16025550147",
    industry: "Automotive",
    state: "AZ",
    timezone: "America/Phoenix",
    status: "voicemail",
    attempts: 1,
    lastCalledAt: T(11, 30),
    consentSource: "list-partner",
    uploadedAt: DAY(15),
  },
  {
    id: "ld_07",
    name: "Bill Hargrove",
    businessName: "Hargrove Hardware",
    phone: "+15035550125",
    industry: "Retail",
    state: "OR",
    timezone: "America/Los_Angeles",
    status: "callback",
    attempts: 1,
    lastCalledAt: T(14, 12),
    consentSource: "web-form",
    uploadedAt: DAY(15),
  },
  {
    id: "ld_08",
    name: "Grace Liu",
    businessName: "Evergreen Medical Group",
    phone: "+12065550190",
    industry: "Medical",
    state: "WA",
    timezone: "America/Los_Angeles",
    status: "interested",
    attempts: 1,
    lastCalledAt: T(15, 3),
    consentSource: "web-form",
    uploadedAt: DAY(15),
  },
  {
    id: "ld_09",
    name: "Frank Boone",
    businessName: "Boone Electrical",
    phone: "+14705550116",
    industry: "Electrical",
    state: "GA",
    timezone: "America/New_York",
    status: "no_answer",
    attempts: 2,
    lastCalledAt: T(10, 5),
    consentSource: "list-partner",
    uploadedAt: DAY(15),
  },
  {
    id: "ld_10",
    name: "Denise Park",
    businessName: "Park Avenue Liquors",
    phone: "+13105550178",
    industry: "Liquor Store",
    state: "CA",
    timezone: "America/Los_Angeles",
    status: "opted_out",
    attempts: 1,
    lastCalledAt: T(9, 33),
    consentSource: "list-partner",
    uploadedAt: DAY(15),
  },
  {
    id: "ld_11",
    name: "Omar Haddad",
    businessName: "Cedar Manufacturing",
    phone: "+13135550152",
    industry: "Manufacturing",
    state: "MI",
    timezone: "America/Detroit",
    status: "calling",
    attempts: 1,
    lastCalledAt: T(15, 45),
    consentSource: "web-form",
    uploadedAt: DAY(15),
  },
  {
    id: "ld_12",
    name: "Janet Wo",
    businessName: "Harbor View Hotel",
    phone: "+18085550137",
    industry: "Hospitality",
    state: "HI",
    timezone: "Pacific/Honolulu",
    status: "pending",
    attempts: 0,
    lastCalledAt: null,
    consentSource: "web-form",
    uploadedAt: DAY(16),
  },
  {
    id: "ld_13",
    name: " Raymond Ellis",
    businessName: "Ellis & Sons Roofing",
    phone: "+16155550143",
    industry: "Contractor",
    state: "TN",
    timezone: "America/Chicago",
    status: "pending",
    attempts: 0,
    lastCalledAt: null,
    consentSource: "web-form",
    uploadedAt: DAY(16),
  },
  {
    id: "ld_14",
    name: "Nina Petrova",
    businessName: "Petrova Wellness Spa",
    phone: "+13055550129",
    industry: "Professional Services",
    state: "FL",
    timezone: "America/New_York",
    status: "pending",
    attempts: 0,
    lastCalledAt: null,
    consentSource: "web-form",
    uploadedAt: DAY(16),
  },
];

export const calls: Call[] = [
  {
    id: "cl_01",
    leadId: "ld_01",
    leadName: "Marcus Reyes",
    businessName: "Reyes Family HVAC",
    startedAt: T(11, 4),
    durationSecs: 214,
    outcome: "interested",
    summary:
      "Owner is expanding to a second truck this fall and open to a working-capital line. Wants a specialist to call back with options. Best time: weekday mornings.",
    numberUsed: "+14155550142",
    recordingUrl: "#recording",
    transcript: [
      { role: "agent", text: "Hi, is this Marcus over at Reyes Family HVAC?", at: 0 },
      { role: "prospect", text: "Yeah, this is Marcus. Who's this?", at: 4 },
      {
        role: "agent",
        text: "Marcus, my name's Ava — I'm an AI assistant calling on behalf of Meridian Capital. We help HVAC businesses access flexible working capital. Do you have a quick minute?",
        at: 6,
      },
      { role: "prospect", text: "Uh, sure, I've got a sec. What's this about?", at: 14 },
      {
        role: "agent",
        text: "Appreciate it. A lot of HVAC owners we talk to are gearing up for the busy season — new trucks, hiring techs, stocking equipment. Is anything like that on your plate right now?",
        at: 18,
      },
      {
        role: "prospect",
        text: "Actually yeah, we're looking at adding a second truck this fall. That's not cheap.",
        at: 27,
      },
      {
        role: "agent",
        text: "That's exactly the kind of thing a working-capital line helps smooth out — you draw what you need for the truck and equipment, and pay it down as jobs come in. Would it be helpful to have one of our loan specialists walk you through the options?",
        at: 34,
      },
      { role: "prospect", text: "Yeah, that'd be worth a conversation. Mornings are best for me.", at: 46 },
      {
        role: "agent",
        text: "Perfect — I'll have a specialist reach out on a weekday morning. Just to confirm, is this the best number to reach you?",
        at: 52,
      },
      { role: "prospect", text: "Yep, this is my cell. Thanks, Ava.", at: 59 },
    ],
  },
  {
    id: "cl_02",
    leadId: "ld_02",
    leadName: "Dr. Priya Nadella",
    businessName: "Bright Smile Dental",
    startedAt: T(10, 22),
    durationSecs: 188,
    outcome: "interested",
    summary:
      "Practice wants to finance a new CBCT imaging machine (~$120k). Interested in equipment financing. Asked about time-to-funding.",
    numberUsed: "+16505550188",
    recordingUrl: "#recording",
    transcript: [
      { role: "agent", text: "Hello, am I speaking with Dr. Nadella?", at: 0 },
      { role: "prospect", text: "Speaking. Go ahead.", at: 3 },
      {
        role: "agent",
        text: "Doctor, I'm Ava, an AI assistant with Meridian Capital — we help dental practices with equipment and expansion financing. Is now an okay time for a quick question?",
        at: 5,
      },
      { role: "prospect", text: "A minute, yes. We've actually been pricing a new imaging machine.", at: 13 },
      {
        role: "agent",
        text: "That's great timing — imaging equipment is one of the most common things we help finance. Roughly what investment are you looking at?",
        at: 20,
      },
      { role: "prospect", text: "The CBCT unit we want is around a hundred and twenty thousand.", at: 28 },
      {
        role: "agent",
        text: "Understood. Equipment financing can spread that over terms that match the machine's useful life, so it doesn't hit cash flow all at once. How quickly are you hoping to move?",
        at: 34,
      },
      { role: "prospect", text: "Ideally within a month or two. How long does funding usually take?", at: 43 },
      {
        role: "agent",
        text: "It varies by file, so I won't quote a timeline myself — but a specialist can give you a realistic answer and the document list. Shall I set that up?",
        at: 49,
      },
      { role: "prospect", text: "Yes, please have them email me first.", at: 58 },
    ],
  },
  {
    id: "cl_03",
    leadId: "ld_03",
    leadName: "Tony Marchetti",
    businessName: "Marchetti's Trattoria",
    startedAt: T(12, 40),
    durationSecs: 96,
    outcome: "callback",
    summary:
      "Mid-lunch rush, couldn't talk. Asked to be called back after 3pm Central. Sounded receptive to discussing seasonal cash flow.",
    numberUsed: "+14155550142",
    callbackAt: T(15, 30),
    recordingUrl: "#recording",
    transcript: [
      { role: "agent", text: "Hi, is this Tony at Marchetti's?", at: 0 },
      { role: "prospect", text: "Yeah but we're slammed right now, it's the lunch rush.", at: 3 },
      {
        role: "agent",
        text: "Totally understand, Tony — I won't hold you. I'm Ava with Meridian Capital, we help restaurants with working capital for slow seasons and equipment. Would after three be a better time to call back?",
        at: 6,
      },
      { role: "prospect", text: "Yeah, after three Central works. We could use a line for the winter dip honestly.", at: 15 },
      {
        role: "agent",
        text: "Perfect, I'll ring you back after three. Thanks for the minute — go take care of your guests.",
        at: 22,
      },
    ],
  },
  {
    id: "cl_04",
    leadId: "ld_05",
    leadName: "Kevin Zhang",
    businessName: "Summit IT Solutions",
    startedAt: T(9, 51),
    durationSecs: 41,
    outcome: "not_interested",
    summary:
      "Recently secured financing through their bank. Not looking for additional capital right now. Polite decline; no opt-out requested.",
    numberUsed: "+16505550188",
    recordingUrl: "#recording",
    transcript: [
      { role: "agent", text: "Hi, is this Kevin with Summit IT Solutions?", at: 0 },
      { role: "prospect", text: "It is. What's this regarding?", at: 3 },
      {
        role: "agent",
        text: "I'm Ava, an AI assistant with Meridian Capital — we help businesses access working capital. Are you exploring any financing at the moment?",
        at: 5,
      },
      { role: "prospect", text: "No, we just set up a line with our bank last quarter. We're all set.", at: 12 },
      {
        role: "agent",
        text: "Got it — sounds like you're in good shape. I'll leave you to it. Thanks for your time, Kevin.",
        at: 19,
      },
    ],
  },
  {
    id: "cl_05",
    leadId: "ld_10",
    leadName: "Denise Park",
    businessName: "Park Avenue Liquors",
    startedAt: T(9, 33),
    durationSecs: 22,
    outcome: "opted_out",
    summary:
      "Requested removal from the calling list. Number added to suppression immediately. No further contact.",
    numberUsed: "+14155550142",
    recordingUrl: "#recording",
    transcript: [
      { role: "agent", text: "Hi, is this Denise at Park Avenue Liquors?", at: 0 },
      { role: "prospect", text: "Take me off your list. I don't want these calls.", at: 3 },
      {
        role: "agent",
        text: "Of course — I've removed you and you won't be contacted again. Sorry for the interruption. Have a good day.",
        at: 6,
      },
    ],
  },
  {
    id: "cl_06",
    leadId: "ld_08",
    leadName: "Grace Liu",
    businessName: "Evergreen Medical Group",
    startedAt: T(15, 3),
    durationSecs: 176,
    outcome: "interested",
    summary:
      "Waiting on insurance reimbursements and wants a bridge for payroll. Strong fit for working capital. Requested a callback this week.",
    numberUsed: "+16505550188",
    recordingUrl: "#recording",
    transcript: [
      { role: "agent", text: "Hi, is this Grace with Evergreen Medical Group?", at: 0 },
      { role: "prospect", text: "Yes, this is Grace.", at: 3 },
      {
        role: "agent",
        text: "Grace, I'm Ava, an AI assistant with Meridian Capital. We help medical groups bridge gaps between insurance reimbursements and payroll. Is cash-flow timing ever a challenge for you?",
        at: 5,
      },
      { role: "prospect", text: "Honestly, yes. Reimbursements lag and payroll doesn't wait.", at: 14 },
      {
        role: "agent",
        text: "That's one of the most common reasons practices use a working-capital line — it covers payroll now and you repay as reimbursements land. Would a specialist call be useful?",
        at: 21,
      },
      { role: "prospect", text: "Yes, sometime this week would be great.", at: 30 },
    ],
  },
];

export function getCallForLead(leadId: string): Call | undefined {
  return calls.find((c) => c.leadId === leadId);
}
